### ISSUE TITLE
(#140) Cayan payment with No signature didn't get updated in IPAD.

### ISSUE THREAD

**Issue by archanamckesson** [rxtrax/tracking#111]
Cayan payment with No signature din't get updated in IPAD

1. Started with $14, Paid $5 and left $9.
2. Paid with Partial FSA Visa card, now remaining amount is $4.50
3. Paid remaining with Full FSA master card and forgot to sign 
4. Cayan payments are not reflected in  IPAD
5. Only allows user to complete delivery transaction by using a  different card because error message 'duplicate' displayed when tried to swipe same card again.

Receipt#: 110215442

**Comment by archanamckesson** [comment]
![img_0006](https://cloud.githubusercontent.com/assets/25255271/22520329/ddf8b8d2-e881-11e6-95f1-998a1abac16e.PNG)

**Comment by brprashanth** [comment]
@jjamminjim, also please observe, 
1. The IPAD has received only $5 in cash, and $4.5 in card.
2. The receipt is not even indicating the credit card details on the receipt.
3. The $4.5 of 2nd paid card is also missing.

**Comment by brprashanth** [comment]
Good afternoon Jason, Jim,

We are facing this issue again.  
The Delivery ID# 1102050 (on QA API Key) was completed today at around noon. However, it has not synchronized even after 2 hrs. We are reopening this issue.
Note: This was the exact transaction that crashed the application. (Have sent a separate email)

I have attached the response we received even after 2 hours since it was completed.
The behavior is still the same we have explained below:
1.	The status is still marked “scheduled” #1102050.
2.	Why is RxTrax returning an incomplete response?. We had discussed this issue earlier couple of times (Issue #111). Issue #111 is currently closed.  Even recently we were told that this has been fixed.
Actually, if we look at the response, we also got responses for the following deliveries "1102048", "1102054","1102055", "2101212". (see attachment)
None of these have been “delivered”. They are coming back to us with the “scheduled” status.
Since this is occurring again, we are reopening this issue.
3.	The Payment types are again coming back as blank (please see the attachment). Screenshot below
Issue #191 was fixed and closed. Now, I see the same behavior on this incomplete transaction.
 
[1102050 QA Api Key.txt](https://github.com/rxtrax/tracking/files/859308/1102050.QA.Api.Key.txt)
