### ISSUE TITLE
(#65) Tax Info Missing When Making Cayan Payment

### ISSUE THREAD

**Issue by jasonmadrid** [rxtrax/tracking#21]
![image](https://cloud.githubusercontent.com/assets/2541528/21629358/bdd47072-d1e4-11e6-85f6-f30523793cf7.png)

**Comment by jjamminjim** [comment]
I am passing the payment-info directly into Cayan, without modification. If the tax-amount is there then it is being sent to Cayan. 

The Cayan docs say something about tax-amount being a level 2 transaction? Not sure what this means, but it looks like, to stage a level 2 transaction, the transaction type must be set to “LEVEL2SALE” instead of just “SALE”  (see [Stage Transaction](https://cayan.com/developers/transactions#stage) for more details). Maybe Arby or Marc can help shed some light on this.

**Comment by brprashanth** [comment]
This issue is not fixed yet. None of the tax amounts are reaching Cayan.
Please find the attached requests.  Also please find some sample Cayan transactions with Tax amounts.

![tax amount 2](https://cloud.githubusercontent.com/assets/8714134/22003649/87dfcd26-dc2b-11e6-9d87-ed46a060f548.png)

[Merchant ware result.pdf](https://github.com/rxtrax/tracking/files/709707/Merchant.ware.result.pdf)
[tax amount.txt](https://github.com/rxtrax/tracking/files/709708/tax.amount.txt)

**Samples**:
[FSA Card - QHP Approval - FSA True Partial Approval.txt](https://github.com/rxtrax/tracking/files/709711/FSA.Card.-.QHP.Approval.-.FSA.True.Partial.Approval.txt)
[EMV AMEX full approval.txt](https://github.com/rxtrax/tracking/files/709710/EMV.AMEX.full.approval.txt)
[EMV AMEX half approval.txt](https://github.com/rxtrax/tracking/files/709712/EMV.AMEX.half.approval.txt)

**Comment by brprashanth** [comment]
This looks to be an issue with Cayan. Closing the issue here. 
Will follow-up with Cayan.
