### ISSUE TITLE
(#82) Killing App Mid Payment Process Causes Completed Transactions To Be Lost

### ISSUE THREAD

**Issue by jasonmadrid** [rxtrax/tracking#27]
All partial payments/full payments fully made and acknowledged by the RxTrax APP are not being REMEMBERED. 
The application crashed during payments and all the successful payments were lost.
These payments showed the payments were already made on the Cayan merchant-ware portal.
Any payments made and acknowledged by RxTrax should be remembered. Currently, the application displays the delivery as a fresh transaction.
Steps:
1. Make a successful payment using credit card and wait until it gets acknowledged by the RxTrax app – the amount section will reflect the totals.
2. Now, select “Pay by check” – crashes in some devices. 
3. Or kill the RxTrax app yourself. Lets see if the IPAD remembers the successful payment information. 
4. Come back to the same delivery item and you can see and it does not reflect the payments made.

**Comment by brprashanth** [comment]
This has been fixed. Note that that the collect payment button was still marked mandatory after the relaunch even after the payments were completed.

Inputs from RxTrax:
The Collect Payment button shows up as “Mandatory” field after re-launching the application after the crash. This is done as per design. This is for the driver to take a look at the payments made so far and confirm.

**Comment by brprashanth** [comment]
The RxTrax application crashes when you attempt to perform the very first Credit card Transaction.
We are seeing this behavior when you peform the very first Credit card transaction - select the Credit card payment and hit “Collect” button for the first time.
We have seen it happening from two separate IPADs and atleast on 4 occasions in the last week or so.
Since it occurred again today on two different systems, we are logging it for tracking.

From our testing today (03/21/2017)
Using Dev API Key
Delivery# 780075

Using QA API key
Delivery# 1102050

When the app crashes, it does not seem to remember anything.
1.	The HIPAA signatures and acceptance is lost
2.	The Customer’s Image, Driver’s License image is lost
3.	If I had made any partial Cash/Check payments, they are lost too.

**Comment by jjamminjim** [comment]
The transactions are now remembered (even in a partial state when using the genius device). The transactions are reloaded when the delivery is opened again for delivery. Genius transactions that have been left in a partial state are verified and completed or cleared as well. 

HIPAA signatures, Customer’s Image, Driver’s License are not saved as part of the transactions until they delivery form is closed and he delivery is completed. These will not be remembered if the app closes/crashes while in the delivery form.
